FROM node:boron

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
COPY bower.json /usr/src/app/
COPY gulpfile.js /usr/src/app/

RUN apt-get update
RUN apt-get install -y ruby-full rubygems-integration
RUN gem install sass

RUN npm install -g bower gulp
COPY . /usr/src/app
RUN bower install --root-allow
RUN npm install && npm cache clean
RUN gulp tasks

CMD ["npm", "start"]
