game:
  build: .
  dockerfile: Dockerfile.local
  volumes:
    - .:/usr/src/app
  ports:
    - "9000:3000"
  links:
    - mongo

mongo:
  image: mongo
  volumes:
    - ./dev-data:/data/db
  ports:
    - "27012:27017"
