game:
  build: .
  ports:
    - "80:80"
  links:
    - mongo
  environment:
    PORT: 80 # this is optional, allows express to use process.env.PORT instead of a raw 80

mongo:
  image: mongo
  ports:
    - "27017:27017"
